FROM nginx:stable-alpine3.17-slim

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/uwsgi_params /etc/nginx/uwsgi_params
COPY nginx/twitter_clone.conf /etc/nginx/conf.d/twitter_clone.conf

CMD /usr/sbin/nginx -g "daemon off;"
